name: mirrorchyan_release

on:
  workflow_dispatch:
    inputs:
      tag:
        default: ''
        required: false
  release:
    types: [released]

jobs:
  mirrorchyan:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'xlxyvergil' }}
    strategy:
      fail-fast: false
      matrix:
        os: [win]
        arch: [x86_64]
    steps:
      - uses: MirrorChyan/uploading-action@v1
        with:
          filetype: latest-release
          filename: ${{ format('MaaFgo-{0}-{1}-*-MXU*', matrix.os, matrix.arch) }}
          mirrorchyan_rid: MaaFgo
          tag: ${{ inputs.tag }}

          os: ${{ matrix.os }}
          arch: ${{ matrix.arch }}

          owner: xlxyvergil
          repo: MaaFgo
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upload_token: ${{ secrets.MirrorChyanUploadToken }}
